import { db } from "./db";
import { scholarships } from "@shared/schema";

const scholarshipData = [
  // STEM Scholarships
  {
    title: "National Merit Scholarship",
    description: "Prestigious scholarship for high-achieving students based on PSAT/NMSQT scores. Recognizes academic excellence and provides financial support for college education.",
    amount: 2500,
    provider: "National Merit Scholarship Corporation",
    deadline: new Date("2025-10-15"),
    applicationUrl: "https://www.nationalmerit.org/s/1758/interior.aspx?sid=1758&gid=2&pgid=424",
    eligibleGrades: [11, 12],
    minGpa: "3.50",
    subjects: ["All Subjects"],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: false,
    requiresRecommendation: false,
    minSat: null,
    minAct: null,
    extracurriculars: [],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["National", "Merit-Based", "Prestige"],
  },
  {
    title: "Google Lime Scholarship",
    description: "For students with disabilities pursuing computer science or related STEM fields. Google is committed to supporting diversity in technology.",
    amount: 10000,
    provider: "Google",
    deadline: new Date("2025-12-01"),
    applicationUrl: "https://www.limeconnect.com/programs/page/google-lime-scholarship",
    eligibleGrades: [11, 12],
    minGpa: "3.70",
    subjects: ["Computer Science", "Engineering", "Mathematics", "Technology"],
    states: [],
    majors: ["Computer Science", "Engineering", "Mathematics", "Information Technology"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: 1400,
    minAct: null,
    extracurriculars: ["Technology Club", "Robotics", "Coding"],
    financialNeedBased: false,
    meritBased: true,
    renewable: true,
    tags: ["STEM", "Technology", "Disability"],
  },
  {
    title: "Intel Science Talent Search",
    description: "One of the nation's most prestigious science research competitions for high school seniors. Recognizes exceptional scientific research projects.",
    amount: 50000,
    provider: "Society for Science",
    deadline: new Date("2025-11-15"),
    applicationUrl: "https://www.societyforscience.org/regeneron-sts/",
    eligibleGrades: [12],
    minGpa: "3.80",
    subjects: ["Science", "Research"],
    states: [],
    majors: ["Biology", "Chemistry", "Physics", "Engineering"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Science Fair", "Research", "Science Club"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["STEM", "Research", "Competition"],
  },
  {
    title: "Microsoft Scholarship",
    description: "For students pursuing degrees in computer science, computer engineering, or related STEM disciplines. Preference given to underrepresented minorities and women.",
    amount: 5000,
    provider: "Microsoft",
    deadline: new Date("2026-02-28"),
    applicationUrl: "https://careers.microsoft.com/students/us/en/usscholarshipprogram",
    eligibleGrades: [12],
    minGpa: "3.00",
    subjects: ["Computer Science", "Engineering"],
    states: [],
    majors: ["Computer Science", "Computer Engineering", "Software Engineering"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: false,
    minSat: null,
    minAct: null,
    extracurriculars: ["Coding", "Technology Club"],
    financialNeedBased: false,
    meritBased: true,
    renewable: true,
    tags: ["STEM", "Technology", "Diversity"],
  },
  
  // State-Specific Scholarships
  {
    title: "California STEM Scholarship",
    description: "Supporting California students pursuing STEM degrees at California colleges and universities.",
    amount: 5000,
    provider: "California STEM Alliance",
    deadline: new Date("2026-03-15"),
    applicationUrl: "https://www.castemscho larship.org",
    eligibleGrades: [12],
    minGpa: "3.20",
    subjects: ["Science", "Mathematics", "Engineering", "Technology"],
    states: ["California"],
    majors: ["Engineering", "Computer Science", "Biology", "Chemistry", "Mathematics"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: 1200,
    minAct: 26,
    extracurriculars: [],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["State-Specific", "STEM", "California"],
  },
  {
    title: "Texas College Access Scholarship",
    description: "Financial aid for Texas residents demonstrating academic achievement and leadership in their communities.",
    amount: 3500,
    provider: "Texas Education Agency",
    deadline: new Date("2026-04-01"),
    applicationUrl: "https://www.texascollegeaccess.org",
    eligibleGrades: [12],
    minGpa: "3.00",
    subjects: [],
    states: ["Texas"],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Community Service", "Leadership"],
    financialNeedBased: true,
    meritBased: true,
    renewable: false,
    tags: ["State-Specific", "Texas", "Leadership"],
  },
  {
    title: "New York STEM Excellence Award",
    description: "Recognizing top STEM students in New York State who plan to pursue STEM degrees and careers.",
    amount: 7500,
    provider: "New York State Education Department",
    deadline: new Date("2026-02-15"),
    applicationUrl: "https://www.nystemexcellence.org",
    eligibleGrades: [12],
    minGpa: "3.50",
    subjects: ["Science", "Mathematics", "Engineering"],
    states: ["New York"],
    majors: ["Engineering", "Computer Science", "Mathematics", "Physics"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: 1300,
    minAct: 28,
    extracurriculars: ["Science Club", "Math Team"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["State-Specific", "STEM", "New York"],
  },
  
  // Arts & Humanities
  {
    title: "Scholastic Art & Writing Awards",
    description: "The nation's longest-running and most prestigious recognition program for creative teenagers in grades 7-12.",
    amount: 10000,
    provider: "Scholastic Inc.",
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.artandwriting.org",
    eligibleGrades: [9, 10, 11, 12],
    minGpa: "2.50",
    subjects: ["Art", "Writing", "Literature"],
    states: [],
    majors: ["Art", "Creative Writing", "English", "Design"],
    ethnicities: [],
    requiresEssay: false,
    requiresRecommendation: false,
    minSat: null,
    minAct: null,
    extracurriculars: ["Art Club", "Writing Club", "Journalism"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["Arts", "Writing", "Creative"],
  },
  {
    title: "National YoungArts Foundation",
    description: "Identifies and supports the most accomplished young artists in the visual, literary, design, and performing arts.",
    amount: 10000,
    provider: "YoungArts",
    deadline: new Date("2025-10-10"),
    applicationUrl: "https://www.youngarts.org",
    eligibleGrades: [10, 11, 12],
    minGpa: "2.80",
    subjects: ["Art", "Music", "Dance", "Theater"],
    states: [],
    majors: ["Fine Arts", "Music", "Dance", "Theater", "Design"],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Art", "Music", "Dance", "Theater"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["Arts", "Performance", "Creative"],
  },
  
  // Athletics & Leadership
  {
    title: "Coca-Cola Scholars Program",
    description: "Recognizing high school seniors for their capacity to lead and serve, as well as their commitment to making a significant impact on their schools and communities.",
    amount: 20000,
    provider: "The Coca-Cola Scholars Foundation",
    deadline: new Date("2025-10-31"),
    applicationUrl: "https://www.coca-colascholars.org",
    eligibleGrades: [12],
    minGpa: "3.00",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Leadership", "Community Service", "Student Government"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["Leadership", "Service", "National"],
  },
  {
    title: "NAIA Athletic Scholarship",
    description: "Athletic scholarships for student-athletes planning to compete at NAIA member institutions.",
    amount: 8000,
    provider: "National Association of Intercollegiate Athletics",
    deadline: new Date("2026-05-01"),
    applicationUrl: "https://www.naia.org",
    eligibleGrades: [12],
    minGpa: "2.30",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: false,
    requiresRecommendation: true,
    minSat: 860,
    minAct: 18,
    extracurriculars: ["Athletics", "Sports"],
    financialNeedBased: false,
    meritBased: true,
    renewable: true,
    tags: ["Athletics", "Sports"],
  },
  
  // Community Service & Social Impact
  {
    title: "Prudential Spirit of Community Award",
    description: "Honors students for outstanding acts of volunteerism and community service.",
    amount: 5000,
    provider: "Prudential Financial",
    deadline: new Date("2025-11-05"),
    applicationUrl: "https://www.prudential.com/links/about/community-spirit-awards",
    eligibleGrades: [9, 10, 11, 12],
    minGpa: "2.00",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Community Service", "Volunteering"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["Service", "Community", "Leadership"],
  },
  {
    title: "AXA Achievement Scholarship",
    description: "Awarded to students who have demonstrated outstanding achievement in their communities and have ambitious goals for the future.",
    amount: 25000,
    provider: "AXA Foundation",
    deadline: new Date("2025-12-15"),
    applicationUrl: "https://www.axa.com/en/about-axa/axa-achievement-scholarship",
    eligibleGrades: [12],
    minGpa: "3.00",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Community Service", "Leadership"],
    financialNeedBased: false,
    meritBased: true,
    renewable: false,
    tags: ["Achievement", "Leadership", "Service"],
  },
  
  // Diversity & Inclusion
  {
    title: "Gates Scholarship",
    description: "Highly selective, full scholarship for exceptional, Pell-eligible, minority high school seniors.",
    amount: 75000,
    provider: "Bill & Melinda Gates Foundation",
    deadline: new Date("2025-09-15"),
    applicationUrl: "https://www.thegatesscholarship.org",
    eligibleGrades: [12],
    minGpa: "3.30",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: ["African American", "Hispanic/Latino", "Native American", "Asian & Pacific Islander"],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Leadership", "Community Service"],
    financialNeedBased: true,
    meritBased: true,
    renewable: true,
    tags: ["Diversity", "Full Ride", "Prestige"],
  },
  {
    title: "Jackie Robinson Foundation Scholarship",
    description: "Four-year scholarship for minority students demonstrating leadership potential, academic excellence, and financial need.",
    amount: 30000,
    provider: "Jackie Robinson Foundation",
    deadline: new Date("2026-02-01"),
    applicationUrl: "https://www.jackierobinson.org",
    eligibleGrades: [12],
    minGpa: "3.00",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: ["African American", "Hispanic/Latino"],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: 1000,
    minAct: 21,
    extracurriculars: ["Leadership", "Community Service"],
    financialNeedBased: true,
    meritBased: true,
    renewable: true,
    tags: ["Diversity", "Leadership", "Minority"],
  },
  
  // General Academic Excellence
  {
    title: "Horatio Alger Scholarship",
    description: "Assists high school students who have faced and overcome great obstacles in their young lives.",
    amount: 25000,
    provider: "Horatio Alger Association",
    deadline: new Date("2025-10-25"),
    applicationUrl: "https://www.horatioalger.org/scholarships/",
    eligibleGrades: [12],
    minGpa: "2.00",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: false,
    minSat: null,
    minAct: null,
    extracurriculars: [],
    financialNeedBased: true,
    meritBased: false,
    renewable: false,
    tags: ["Need-Based", "Overcoming Adversity"],
  },
  {
    title: "Dell Scholars Program",
    description: "Recognizes students who have overcome significant obstacles to pursue their education.",
    amount: 20000,
    provider: "Michael & Susan Dell Foundation",
    deadline: new Date("2026-01-15"),
    applicationUrl: "https://www.dellscholars.org",
    eligibleGrades: [12],
    minGpa: "2.40",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: [],
    financialNeedBased: true,
    meritBased: false,
    renewable: true,
    tags: ["Need-Based", "Perseverance"],
  },
  {
    title: "Elks National Foundation Most Valuable Student Scholarship",
    description: "Awards for high school seniors based on scholarship, leadership, and financial need.",
    amount: 12500,
    provider: "Elks National Foundation",
    deadline: new Date("2025-11-08"),
    applicationUrl: "https://www.elks.org/scholars/scholarships/MVS.cfm",
    eligibleGrades: [12],
    minGpa: "3.50",
    subjects: [],
    states: [],
    majors: [],
    ethnicities: [],
    requiresEssay: true,
    requiresRecommendation: true,
    minSat: null,
    minAct: null,
    extracurriculars: ["Leadership", "Community Service"],
    financialNeedBased: true,
    meritBased: true,
    renewable: true,
    tags: ["Leadership", "Service", "Need-Based"],
  },
];

async function seedScholarships() {
  try {
    console.log("Seeding scholarships...");
    
    // Insert all scholarships
    const result = await db.insert(scholarships).values(scholarshipData).returning();
    
    console.log(`Successfully seeded ${result.length} scholarships`);
    process.exit(0);
  } catch (error) {
    console.error("Error seeding scholarships:", error);
    process.exit(1);
  }
}

seedScholarships();
